#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  # merge-default-rules: false
  # Set the formatter to 'html'
  # formatter: html
  # Output file instead of logging results
  # output-file: 'linters/sass-lint.html'
# File Options
files:
  ignore:
    - 'site/sass/vendor/**/*.*'
    - 'site/sass/core/_utils.scss'
    - 'site/sass/core/_defaults.scss'
    - 'site/sass/core/_grid.scss'
#   include:
#    - 'site/src/_source/sass/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  bem-depth:
    - 0
    - max-depth: 3
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 0
  no-debug: 0
  no-ids: 0
  no-important: 0
  no-color-literals: 0
  indentation:
    - 1
    - size: 4
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 0
    -
      properties:
        - margin
        - content
  no-css-comments: 0
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
